# 运动相关设置

# 需要生成的运动类别
  # // spin
  # SineSpin : 0
  # UniformSpin : 1
  # RandomSpin : 2
  
  # // translate
  # UniformTranslate : 3
  # VariationTranslate : 4

  # // mixed
  # SineUniform : 5
  # SineVariation : 6
  # UniformUniform : 7
  # UniformVariation : 8
  # RandomUniform : 9
  # RandomVariation : 10

motion_type: 1